// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLuSi32fAnizaIic6IEjDAguq5RfXsF0',
    appId: '1:879564388991:web:b260c81f4eef5e41821d4a',
    messagingSenderId: '879564388991',
    projectId: 'practice-e7fff',
    authDomain: 'practice-e7fff.firebaseapp.com',
    storageBucket: 'practice-e7fff.appspot.com',
    measurementId: 'G-QPQH459D06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVdVg8f9nAV5_iYRJaDzjSjGBrKWSDmQ',
    appId: '1:879564388991:android:d97f925503e3eeca821d4a',
    messagingSenderId: '879564388991',
    projectId: 'practice-e7fff',
    storageBucket: 'practice-e7fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9M0Rao50daKrqhmVxgcKCBMkt3GkgJ4U',
    appId: '1:879564388991:ios:cd17a71758ecb8bf821d4a',
    messagingSenderId: '879564388991',
    projectId: 'practice-e7fff',
    storageBucket: 'practice-e7fff.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9M0Rao50daKrqhmVxgcKCBMkt3GkgJ4U',
    appId: '1:879564388991:ios:cd17a71758ecb8bf821d4a',
    messagingSenderId: '879564388991',
    projectId: 'practice-e7fff',
    storageBucket: 'practice-e7fff.appspot.com',
    iosBundleId: 'com.example.practice',
  );
}
